<a href="https://colab.research.google.com/github/skhazaei/TensorFlow-repo/blob/master/Sequential_model_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Keras Project: [keras.io](https://keras.io)

- The Keras Project was authored by Francois Chollet.
- It's a high-level neural networks API developed with the goal making easy to build giant deep learning models.
- It was developed as an API without backend and actually it supports multiple backend implementations.
- In TensorFlow 2, Keras API is adopted as the high-level API.

# Build a Feedforward neural network model:
 3 dense layers: 
 - the firs two layers have 16 units with ReLU activation function (Rectifier Unit).
 - the last layer, 10 units with softmax activation function. 
 - the input images are (28, 28) pixels.

In [2]:
import tensorflow as tf


model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28, 28)),
                                    tf.keras.layers.Dense(16, activation='relu'),
                                    tf.keras.layers.Dense(16, activation='relu'),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 16)                12560     
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


### Note that `None` in `model.summary()` refers to the batch size.

## Print the initialized weights of the model

In [4]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[ 0.05890848, -0.06756742,  0.00085027, ...,  0.0577492 ,
         -0.03248112,  0.01044136],
        [-0.07207966, -0.08429477, -0.07263003, ...,  0.0016764 ,
         -0.02521231,  0.00986537],
        [ 0.02813379,  0.00461442,  0.01070222, ..., -0.02112783,
          0.00387261, -0.04615775],
        ...,
        [-0.04236224, -0.02467112, -0.06013386, ...,  0.07274468,
         -0.06386082,  0.06631045],
        [ 0.07251616, -0.01730909, -0.02251616, ...,  0.0415549 ,
          0.0556498 , -0.04028326],
        [ 0.08277085, -0.00098564, -0.04993736, ..., -0.0794448 ,
          0.06374775, -0.07709312]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[ 3.7862659e-03,  3.6248043e-01,  1.7943233e-02, -

# Convolutional and pooling layers

**Build a convolutional neural network model**

- The first layer is a convolutional layer with 16 filters, a kernel size of 3 times 3, a ReLu activation function, and an input shape of 28 times 28 times 1.

In [5]:
model = tf.keras.models.Sequential([tf.keras.layers.Conv2D(16, kernel_size=3, activation='relu', input_shape=(28, 28, 1))])

In [6]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 16)        160       
Total params: 160
Trainable params: 160
Non-trainable params: 0
_________________________________________________________________


* Note that `input_shape` must have 3 dimensions as input for `Conv2D` layer. The third index indicates the number of channels.


**Complete the model**
- Add a pooling layer of pool size 3 times 3.
- Add a flatten layer
- Add a dense layer with 10 units and a softmax activation function.

In [7]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Conv2D(16, kernel_size=3, activation='relu', input_shape=(28, 28, 1)),
                                    tf.keras.layers.MaxPooling2D(3,3),
                                    tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [8]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 16)        160       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 8, 8, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                10250     
Total params: 10,410
Trainable params: 10,410
Non-trainable params: 0
_________________________________________________________________


### To preserve the input and output dimensions of `Conv2D` layer, set `padding='same'`

In [9]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Conv2D(16, kernel_size=3, activation='relu', input_shape=(28, 28, 1), padding='same'),
                                    tf.keras.layers.MaxPooling2D(3,3),
                                    tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [10]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 28, 28, 16)        160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 9, 9, 16)          0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 1296)              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                12970     
Total params: 13,130
Trainable params: 13,130
Non-trainable params: 0
_________________________________________________________________


### Try `strides=2`, which means "the stride is two in every dimension".

In [11]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Conv2D(16, kernel_size=3, activation='relu', input_shape=(28, 28, 1),
                                                           padding='same', strides=2),
                                    tf.keras.layers.MaxPooling2D(3,3),
                                    tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [12]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 14, 14, 16)        160       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2570      
Total params: 2,730
Trainable params: 2,730
Non-trainable params: 0
_________________________________________________________________


### the value of `data_format` argument by default is `data_format='channels_last'`. This can be modified as `data_format='channels_first'`. Do not forget to define `data_format` in pooling layer as well, to have exactly the same neural network as before.

In [13]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Conv2D(16, kernel_size=3, activation='relu',
                                                           input_shape=(1, 28, 28), data_format='channels_first'),
                                    tf.keras.layers.MaxPooling2D((3,3), data_format='channels_first'),
                                    tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [14]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 16, 26, 26)        160       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 16, 8, 8)          0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_6 (Dense)              (None, 10)                10250     
Total params: 10,410
Trainable params: 10,410
Non-trainable params: 0
_________________________________________________________________


# Compile method

In [15]:
model.compile(optimizer='Adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

## Check what is stored in the model (model attributes):

In [16]:
print(model.loss)
print(model.optimizer)
print(model.metrics)

sparse_categorical_crossentropy
[]


In [19]:
model = tf.keras.models.Sequential([tf.keras.layers.Dense(64, activation='elu', input_shape=(32,)),
                                    tf.keras.layers.Dense(1, activation='sigmoid')])
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy', 'mae'])
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 64)                2112      
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 65        
Total params: 2,177
Trainable params: 2,177
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.optimizer

In [29]:
model.compile(optimizer=tf.keras.optimizers.SGD(),
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=[tf.keras.metrics.MeanAbsoluteError(), tf.keras.metrics.BinaryAccuracy()])

# The difference between `sparse_categorical_crossentropy` and `categorical_crossentropy` loss function:

- `categorical_crossentropy`: if the labels have been represented as a one-hot vector, so each row of y_train is a vector of length num_classes which is all zeros, excet for a one in the place corresponding to the correct class. 

- `sparse_categorical_crossentropy`: if all the labels have a sparse representation, so just a single integer for each label, then y_train could be a one-dimensional array with length equal to the number of samples.